/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Cubo;

import GUI.Front;
import java.util.regex.*;
import java.util.StringTokenizer;
import Mapeo.*;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JTable;

/**
 *
 * @author eddytrex
 */
public class VistaCuboE extends javax.swing.JFrame {

    public Modelo a;
    public Olap es;
    public ModeloEstrella mode;
    private CuboE cuboE;
    public ArrayList<Dimension> dx1 = new ArrayList();

    /**
     * Creates new form VistaCuboE
     */
    public VistaCuboE() {
        initComponents();
        this.jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    }

    public void addDim(String nombreA, ArrayList<String> j, String Nombre) {
        es.setDimX1(nombreA, j, Nombre);
    }

    public void setModeloMetricas(Modelo m, ArrayList<String> metricas, String th) {
        this.a = m;
        this.a.cargarEntidades();
        this.a.ejecutaSecuencia();

        this.es = new Olap(a, th, metricas);


        Iterator<String> metrica = metricas.iterator();
        while (metrica.hasNext()) {
            String me = metrica.next();
            this.jCM1.addItem(me);
        }
        this.jCM1.addItem("");
        metrica = metricas.iterator();
        while (metrica.hasNext()) {
            String me = metrica.next();
            this.jCM2.addItem(me);
        }
        this.jCM2.addItem("");
        this.jCO.addItem("+");
        this.jCO.addItem("-");
        this.jCO.addItem("*");
        this.jCO.addItem("/");

    }

    public void setOlap(Olap t) {
        this.es = t;

        Iterator<Dimension> temp = this.es.getDimX1().iterator();
        while (temp.hasNext()) {
            this.jCb.addItem(temp.next().NombreDim);
        }

        Iterator<String> metrica = es.getMetricas().iterator();
        while (metrica.hasNext()) {
            String me = metrica.next();
            this.jCM1.addItem(me);
        }
        this.jCM1.addItem("");
        metrica = es.getMetricas().iterator();
        while (metrica.hasNext()) {
            String me = metrica.next();
            this.jCM2.addItem(me);
        }
        this.jCM2.addItem("");
        
        this.jCO.addItem("+");
        this.jCO.addItem("-");
        this.jCO.addItem("*");
        this.jCO.addItem("/");

    }

    public void generarTH(String nombre) {


        this.es.generaTablaEchos(nombre);

        mode = es.getModeloEstrella();
        mode.setMetricas(es.getMetricas());


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jt1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jtX = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jtY = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jtZ = new javax.swing.JTextField();
        jCb = new javax.swing.JComboBox();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jmetricas = new javax.swing.JTextField();
        jCM1 = new javax.swing.JComboBox();
        jCM2 = new javax.swing.JComboBox();
        jCO = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Prueba");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Drill Down X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Dirll Up X");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Drill Down Y");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Dirll Up y");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Dice");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        jButton7.setText("Slide X");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Slide Y");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Slide Z");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Add Dimension");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("CrearCubo");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addGap(37, 37, 37)
                        .addComponent(jmetricas, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCM1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCO, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCM2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jtZ, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtY, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtX, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCb, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7)
                            .addComponent(jtY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8)
                            .addComponent(jButton9)
                            .addComponent(jtZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jt1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton11)
                            .addComponent(jmetricas)
                            .addComponent(jCM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Front.URL = "jdbc:postgresql://127.0.0.1:5432/prueba";
        Front.user = "postgres";
        Front.password = "postgres";
        a = new Modelo();
        a.cargarEntidades();
        a.ejecutaSecuencia();
        // Entidad prueba=a.BuscarEntidad("agencia");                        
        //ArrayList<String> dimensiones=a.getDimensiones("detallefactura");           
        ArrayList<Entidad> x = a.getEntidades();

        ArrayList<String> metricas = new ArrayList();

        metricas.add("quantity");
        es = new Olap(a, "orden", metricas);

        ArrayList<String> jeraquia = new ArrayList();

        //jeraquia.add("pais_nombre");
        //jeraquia.add("departamento_nombre");
        //jeraquia.add("municipio_nombre");
        //jeraquia.add("agencia_nombre");           

        jeraquia.add("pais_country");
        jeraquia.add("cliente_firstname");

        es.setDimX1("dimension_01", jeraquia, "cliente");




        //Dimension dim=new Dimension(a.getDimOriginales().get(1),jeraquia);         

        //a.getDimOriginales().get(1).CrearDimensionTiempo("factura_fecha");

        //dim.CrearDimension("Ubicacion");

        jeraquia = new ArrayList();

        jeraquia.add("categoria_categoryname");
        jeraquia.add("producto_title");
        //jeraquia.add("producto_nombre");

        es.setDimX1("dimension_02", jeraquia, "producto");

        //es.setDimTiempo("dimension_02", "factura_fecha");

        jeraquia = new ArrayList();
        jeraquia.add("vendedor_vendor_name");


        es.setDimX1("dimension_03", jeraquia, "vendedor");

        // ya introducidas las dimenciones con jerarquias se coloca el nombre de la tabla hechos.  este metodo crea un Atributo de Olap(estrella) 
        es.generaTablaEchos("prueba");
        //TODO: 
        //estrella tiene los campos  de la tabla hechos, las llaves foraneas  (hacia las dimenciones) y las dimenciones con jeraquias.
        mode.setMetricas(metricas);
        mode = es.getModeloEstrella();

        cuboE = new CuboE(mode, mode.dimX1, 1);

        this.jTable1.setModel(cuboE.tm);


        // this.jTable1.setModel(cuboE.tm);

    }//GEN-LAST:event_jButton1ActionPerformed

    public void AddDim(Dimension x1) {
        this.dx1.add(x1);
    }

    public void CrearCubo() {

        if (this.dx1.size() == 3) {
            cuboE = new CuboE(this.mode, this.dx1, 1);
        }


    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cuboE.DirllDownX();
        this.jTable1.setModel(cuboE.tm);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        cuboE.DrillUpX();
        this.jTable1.setModel(cuboE.tm);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        cuboE.DrillDownY();
        this.jTable1.setModel(cuboE.tm);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        cuboE.DirllUpY();
        this.jTable1.setModel(cuboE.tm);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        cuboE.Dice(this.jt1.getText());
        this.jTable1.setModel(cuboE.tm);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Pattern iPa = Pattern.compile("^\\d*$");
        Matcher matchesInteger = iPa.matcher(this.jtX.getText());
        if (matchesInteger.matches()) {
            int itemsX = Integer.parseInt(this.jtX.getText());
            cuboE.Slide("x", itemsX);
        } else {
            ArrayList<String> a = new ArrayList();

            StringTokenizer tok = new StringTokenizer(this.jtX.getText(), "|");
            while (tok.hasMoreTokens()) {
                a.add(tok.nextToken());

            }

            String sa[] = new String[a.toArray().length];
            for (int i = 0; i < a.toArray().length; i++) {
                sa[i] = (String) a.toArray()[i];

            }

            cuboE.Slide("x", sa);

        }
        this.jTable1.setModel(cuboE.tm);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        Pattern iPa = Pattern.compile("^\\d*$");
        Matcher matchesInteger = iPa.matcher(this.jtY.getText());
        if (matchesInteger.matches()) {
            int itemsY = Integer.parseInt(this.jtY.getText());
            cuboE.Slide("y", itemsY);
        } else {
            ArrayList<String> a = new ArrayList();

            StringTokenizer tok = new StringTokenizer(this.jtY.getText(), "|");
            while (tok.hasMoreTokens()) {
                a.add(tok.nextToken());
            }

            String sa[] = new String[a.toArray().length];
            for (int i = 0; i < a.toArray().length; i++) {
                sa[i] = (String) a.toArray()[i];

            }
            cuboE.Slide("y", sa);

        }
        this.jTable1.setModel(cuboE.tm);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int itemsZ = Integer.parseInt(this.jtZ.getText());
        cuboE.Slide("z", itemsZ);
        this.jTable1.setModel(cuboE.tm);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String Name = (String) this.jCb.getSelectedItem();
        this.jCb.removeItem(Name);
        if (this.dx1.size() < 3) {
            this.dx1.add(this.es.getDimension(Name));
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        if (this.dx1.size() == 3) {
            //int imetica = Integer.parseInt(this.jmetricas.getText());

            String m1 = (String) this.jCM1.getSelectedItem();
            String m2 = (String) this.jCM2.getSelectedItem();
            String o = (String) this.jCO.getSelectedItem();
            String total="";
            if(!m1.equals("")&&!m2.equals(""))
            {
             total = m1 + o + m2;
            }
            else if(!m1.equals("")&&m2.equals(""))
            {
            total=m1;
            }
            else if(m1.equals("")&&!m2.equals(""))
            {
              total=m2;  
            }
            
            //cuboE = new CuboE(mode,this.dx1,imetica);
            cuboE = new CuboE(mode, this.dx1, total);

            this.jTable1.setModel(cuboE.tm);
        }

    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCuboE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCuboE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCuboE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCuboE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VistaCuboE().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jCM1;
    private javax.swing.JComboBox jCM2;
    private javax.swing.JComboBox jCO;
    private javax.swing.JComboBox jCb;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jmetricas;
    private javax.swing.JTextField jt1;
    private javax.swing.JTextField jtX;
    private javax.swing.JTextField jtY;
    private javax.swing.JTextField jtZ;
    // End of variables declaration//GEN-END:variables
}
